version: '3.1'

services:
  web:
    build: packages/client
    ports:
      - "80:80"
  server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE_NAME=server
        - SERVICE_PATH=./apps/server
        - SERVICE_PORT=3000
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-ui:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis

