version: '3.1'

services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE_NAME=client
        - SERVICE_PATH=./apps/client
        - SERVICE_PORT=80
    ports:
      - "80:80"
    environment:
      - BASE_URL=http://server:3000
    depends_on:
      - server
  server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PACKAGE_NAME=server
        - SERVICE_PATH=./apps/server
        - SERVICE_PORT=3000
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
  redis-ui:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    depends_on:
      - redis

