version: '3.1'

services:
  web:
    build: packages/client
    ports:
      - "80:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-ui:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis

